# Generated by Django 2.2.6 on 2019-10-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IceCream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor', models.CharField(max_length=255)),
                ('base', models.CharField(choices=[('vanilla', 'vanilla'), ('chocolate', 'chocolate')], max_length=255)),
                ('available', models.CharField(choices=[('daily', 'daily'), ('weekly', 'weekly'), ('seasonal', 'seasonal')], max_length=255)),
                ('featured', models.BooleanField()),
                ('date_churned', models.DateField()),
                ('url', models.TextField(null=True)),
            ],
        ),
    ]
