# Generated by Django 2.2.6 on 2019-10-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icecream',
            name='available',
            field=models.CharField(choices=[('daily', 'daily'), ('weekly', 'weekly'), ('seasonal', 'seasonal'), ('featured', 'featured')], max_length=255),
        ),
    ]
